# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

variables:
  buildConfiguration: 'Release'

stages:
- stage: CI
  displayName: CI stage
  jobs:
  - job: build
    displayName: Build
    steps:
    - script: echo This is a BUILD job
      displayName: 'Build project'
      
- stage: CD
  displayName: CD stage
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: VMs
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: echo This is a DEPLOYMENT job
            displayName: 'Deploy project'

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/Install-MicrosoftTeams.ps1'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
