trigger:
- master

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: PowerShell@2
   inputs:
     filePath: '$(System.DefaultWorkingDirectory)/Install-MicrosoftTeams.ps1'
